import json
import sys
from pathlib import Path

# Ensure project root is on sys.path
PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

GPT_KEY_PATH = PROJECT_ROOT.parent / "api_keys" / "azure_cloudbank" / "gpt-4o-lufeng.txt"
EMBEDDING_KEY_PATH = PROJECT_ROOT.parent / "api_keys" / "azure_cloudbank" / "embedding.txt"
CACHE_DIR = PROJECT_ROOT / "embedding" / "paper"

from core.ask import ask
from core.get_provenance_node import find_provenance_node
from core.tree_gen import phrase_visual_pattern_extraction


def extract_full_text(pdf_path: Path) -> str:
    """
    Extract full text from a PDF using the OCR-enabled phrase_visual_pattern_extraction pipeline.

    Args:
        pdf_path: Path to the PDF file.

    Returns:
        Complete text string assembled from all extracted phrases.
    """
    print("Running OCR to extract full document text...")
    phrases = phrase_visual_pattern_extraction(str(pdf_path))
    text_parts = [item.get("phrase", "").strip() for item in phrases if item.get("phrase")]
    full_text = " ".join(text_parts).strip()

    if not full_text:
        raise ValueError(f"No textual content extracted from {pdf_path}")

    return full_text


def main() -> None:
    """
    Simple harness to run find_provenance_node against the first merged paper JSON.
    The expected answer is generated by calling GPT over the document's full text.
    """
    question = "What is the publication year of this paper? Return only a number." 

    output_dir = PROJECT_ROOT / "output" / "paper"
    merged_files = sorted(output_dir.glob("*_merged.json"))
    if not merged_files:
        raise FileNotFoundError(f"No merged JSON files found in {output_dir}")

    merged_json_path = merged_files[0]
    pdf_stem = merged_json_path.stem.replace("_merged", "")

    paper_dir = PROJECT_ROOT / "data" / "paper"
    pdf_candidates = list(paper_dir.glob("*.pdf"))
    pdf_path = next((p for p in pdf_candidates if p.stem == pdf_stem), None)
    if pdf_path is None:
        raise FileNotFoundError(
            f"Could not find matching PDF for {pdf_stem} in {paper_dir}. "
            "Please update the script with the correct PDF path."
        )

    print(f"Running provenance search for PDF: {pdf_path}")
    print(f"Using merged JSON: {merged_json_path}")

    full_text = extract_full_text(pdf_path)
    print("Generating expected answer via GPT...")
    #expected_answer = ask(full_text, question, key_path=str(GPT_KEY_PATH))
    expected_answer = "2016"
    #print(f"Expected answer: {expected_answer}")

    CACHE_DIR.mkdir(parents=True, exist_ok=True)

    result = find_provenance_node(
        pdf_path=str(pdf_path),
        merged_json_path=str(merged_json_path),
        question=question,
        answer=expected_answer,
        cache_dir=str(CACHE_DIR),
        gpt_key_path=str(GPT_KEY_PATH),
        embedding_key_path=str(EMBEDDING_KEY_PATH),
    )

    if result:
        print("\nFound matching header:")
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print("\nNo matching header found.")


if __name__ == "__main__":
    main()

