"""
MinerU -> Docling Format Adapter

Converts MinerU content_list into a docling-like dict accepted by tree_reconstructor.

content_list format (generated by vlm/pipeline union_make):
- Flat list, each block contains page_idx (0-indexed)
- bbox normalized to 0-1000 (based on page_size)
- Title blocks: type="text" + text_level field
- Text blocks: type="text" (no text_level)
"""

import logging
from collections import defaultdict
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Header text appearing on >= this many pages is treated as a running header
_RUNNING_HEADER_MIN_PAGES = 2

# MinerU content_list type -> docling label mapping
_TYPE_TO_LABEL = {
    "text": "text",  # becomes section_header when text_level is present
    "ref_text": "text",
    "equation": "text",
    "code": "text",  # code blocks treated as plain text
    "aside_text": "text",  # aside notes (arXiv sidebars, etc.)
    # "header" is not in this mapping -- dynamically decided by pre-scan frequency logic
    "footer": "page_footer",  # auxiliary text (page footer)
    "page_footnote": "footnote",
}

# Types to skip
_SKIP_TYPES = {"page_number"}


def _convert_bbox_to_docling(
    bbox_norm: list[int],
    pdf_w: float,
    pdf_h: float,
) -> dict[str, Any]:
    """Convert content_list normalized bbox (0-1000, TL origin) to docling BOTTOMLEFT bbox (PDF pts)."""
    x0, y0, x1, y1 = bbox_norm
    l = x0 / 1000 * pdf_w
    r = x1 / 1000 * pdf_w
    # TL -> BL: flip y
    t_bl = pdf_h - (y0 / 1000 * pdf_h)
    b_bl = pdf_h - (y1 / 1000 * pdf_h)
    return {"l": l, "t": t_bl, "r": r, "b": b_bl, "coord_origin": "BOTTOMLEFT"}


def convert_mineru_to_docling_format(
    mineru_data: dict,
    pdf_path: Path,
) -> dict:
    """
    Convert MinerU content_list into a docling-like dict accepted by tree_reconstructor.

    Args:
        mineru_data: MinerU JSON (containing content_list and middle_json)
        pdf_path: Original PDF path (used to get page dimensions in pts)

    Returns:
        docling-like dict: {pages, texts, tables}
    """
    import fitz

    content_list = mineru_data.get("content_list", [])
    if not content_list:
        raise ValueError(
            "MinerU data missing content_list; re-parse with the latest mineru_tool"
        )

    # Get PDF page dimensions (pts) via fitz
    doc = fitz.open(str(pdf_path))
    pages: dict[str, dict] = {}
    page_dims: dict[int, tuple[float, float]] = {}  # page_no -> (w, h)
    for i in range(len(doc)):
        page = doc[i]
        w, h = page.rect.width, page.rect.height
        page_no = i + 1
        pages[str(page_no)] = {"size": {"width": w, "height": h}, "page_no": page_no}
        page_dims[page_no] = (w, h)
    doc.close()

    # Pre-scan: count how many distinct pages each header text appears on,
    # distinguishing running headers from misclassified titles
    header_page_sets: dict[str, set[int]] = defaultdict(set)
    for item in content_list:
        if item.get("type") == "header":
            text = item.get("text", "").strip()
            if text:
                header_page_sets[text].add(item.get("page_idx", 0))
    repeated_headers: set[str] = {
        t
        for t, pages in header_page_sets.items()
        if len(pages) >= _RUNNING_HEADER_MIN_PAGES
    }

    texts: list[dict] = []
    skip_count = 0

    for item in content_list:
        page_idx = item.get("page_idx", 0)
        page_no = page_idx + 1
        dims = page_dims.get(page_no)
        if not dims:
            skip_count += 1
            continue
        pdf_w, pdf_h = dims

        item_type = item.get("type", "")

        # Skip unwanted types
        if item_type in _SKIP_TYPES:
            continue

        # Extract caption from image blocks
        if item_type == "image":
            _extract_nested_captions(
                item,
                "image_caption",
                page_no,
                pdf_w,
                pdf_h,
                texts,
            )
            continue

        # Extract content from table blocks
        if item_type == "table":
            _process_table_block(item, page_no, pdf_w, pdf_h, texts)
            continue

        # list type: concatenate list_items
        if item_type == "list":
            list_items = item.get("list_items", [])
            text = "\n".join(li.strip() for li in list_items if li and li.strip())
            label = "text"
        elif item_type == "header":
            # Frequency classification: cross-page repeated -> page_header,
            # single occurrence -> text (possibly misclassified title)
            text = item.get("text", "").strip()
            label = "page_header" if text in repeated_headers else "text"
        else:
            # Standard text types
            label = _TYPE_TO_LABEL.get(item_type)
            if label is None:
                skip_count += 1
                continue
            text = item.get("text", "").strip()
            # Title block: has text_level field
            if item_type == "text" and "text_level" in item:
                label = "section_header"

        if not text:
            continue

        # bbox conversion
        bbox_norm = item.get("bbox")
        if bbox_norm and len(bbox_norm) == 4:
            bbox_dict = _convert_bbox_to_docling(bbox_norm, pdf_w, pdf_h)
        else:
            bbox_dict = {
                "l": 0,
                "t": pdf_h,
                "r": pdf_w,
                "b": 0,
                "coord_origin": "BOTTOMLEFT",
            }

        entry: dict[str, Any] = {
            "label": label,
            "text": text,
            "prov": [{"page_no": page_no, "bbox": bbox_dict}],
        }
        if item_type == "aside_text":
            entry["is_aside_text"] = True

        texts.append(entry)

    if skip_count > 0:
        logger.debug(f"Skipped {skip_count} unprocessable content_list blocks")

    logger.info(f"MinerU -> docling conversion done: {len(texts)} texts, {len(pages)} pages")

    return {"pages": pages, "texts": texts, "tables": []}


def _extract_nested_captions(
    item: dict,
    caption_key: str,
    page_no: int,
    pdf_w: float,
    pdf_h: float,
    texts: list[dict],
) -> None:
    """Extract captions from image/table blocks as independent text entries."""
    captions = item.get(caption_key, [])
    bbox_norm = item.get("bbox")
    if bbox_norm and len(bbox_norm) == 4:
        bbox_dict = _convert_bbox_to_docling(bbox_norm, pdf_w, pdf_h)
    else:
        bbox_dict = {
            "l": 0,
            "t": pdf_h,
            "r": pdf_w,
            "b": 0,
            "coord_origin": "BOTTOMLEFT",
        }

    for cap in captions:
        cap_text = cap.strip() if isinstance(cap, str) else ""
        if cap_text:
            texts.append(
                {
                    "label": "text",
                    "text": cap_text,
                    "prov": [{"page_no": page_no, "bbox": bbox_dict}],
                }
            )


def _process_table_block(
    item: dict,
    page_no: int,
    pdf_w: float,
    pdf_h: float,
    texts: list[dict],
) -> None:
    """Process table block: extract caption and body text."""
    bbox_norm = item.get("bbox")
    if bbox_norm and len(bbox_norm) == 4:
        bbox_dict = _convert_bbox_to_docling(bbox_norm, pdf_w, pdf_h)
    else:
        bbox_dict = {
            "l": 0,
            "t": pdf_h,
            "r": pdf_w,
            "b": 0,
            "coord_origin": "BOTTOMLEFT",
        }

    # Extract caption
    for cap in item.get("table_caption", []):
        cap_text = cap.strip() if isinstance(cap, str) else ""
        if cap_text:
            texts.append(
                {
                    "label": "text",
                    "text": cap_text,
                    "prov": [{"page_no": page_no, "bbox": bbox_dict}],
                }
            )

    # Extract table body HTML as text (no table structuring for now)
    body_html = item.get("table_body", "")
    if body_html and isinstance(body_html, str):
        texts.append(
            {
                "label": "text",
                "text": body_html.strip(),
                "prov": [{"page_no": page_no, "bbox": bbox_dict}],
            }
        )
